infra/repository内のNewXXXRepositoryの引数を変更する
temmie524/room-management-app-backend pull request #25
Opened 2023-08-26 07:57 UTC by temmie524

※XXXにはUserかReservationかRoomが入る

## 目的
infra/repositoryとdomain/repoでDIするため

## やったこと
1. infrastructure/XXX/Sql_handlerは削除
2. infrastructure/mysqlの変更
3. NewSqlHandler -> NewDBに変更。SqlHandlerではなく*gorm.DBを返す形になる。
4. NewXXXRepositoryの変更。引数に *gorm.DBを取り、domain/reservation.RepositoryのInterfaceを返す
5. その実態の処理も変更。GORMを使った関数を利用。

2023-08-27 01:30 UTC, TakumaKurosawa requested changes

2023-08-27 01:30 UTC, TakumaKurosawa commented on infrastructure/mysql.go
> +/*
この辺り、もう不要そうであればコメントアウトではなく、削除しちゃいましょう！
Gitの履歴には残っているはずなので！

2023-08-27 01:30 UTC, TakumaKurosawa commented on infrastructure/repository/reservation/sql_handler.go
>  }
これも消してしまって良さそう

2023-08-27 01:30 UTC, TakumaKurosawa commented on infrastructure/repository/user/user.go
> +func (repo *UserRepository) FindByEmail(u *model.User, email string) error {
今の実装だと、他の実装箇所もそうですが副作用のある関数になってしまっています。
下記のような形で副作用のない関数に作り直しましょう！

```go
func (repo *UserRepository) FindByEmail(email string) (*model.User, error) {
  // 取得処理
}
```

2023-08-27 01:30 UTC, TakumaKurosawa commented on infrastructure/router.go
> +		//CookieMaxAge: 60,
この辺もTODOコメントとするか、消してしまって良さそう

2023-08-27 01:30 UTC, TakumaKurosawa commented on infrastructure/router.go
> +	userController := usco.NewUserController(*userUsecase)
UseCase層もInterfaceを作って、DIしてあげるとテストが書きやすいです

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/reservation/reservation.go
>  	id, _ := strconv.Atoi(c.Param("id"))
エラーハンドリングが抜けている

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/user/user.go
> +	cookie.SameSite = http.SameSiteNoneMode
こう書けそう？

```suggestion
	cookie := http.Cookie{
	  Name: "token",
	  // ...
	}
```

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/user/user.go
> +	cookie.Secure = true //postman確認時コメントアウト
TODOコメントにしておくと良さそう

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/user/user.go
> +	token := c.Get("csrf").(string)
okチェックもしてあげた方が良さそう

```suggestion
	token, ok := c.Get("csrf").(string)
	if !ok {
	  // エラー処理
	}
```

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/user/user.go
> +	return c.JSON(201, "deleted")
Webを支える技術という本を是非読んでください！

直接数字を参照するのではなく、 `http.ServerStatusOK` 定数を使いましょう！

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/user/user.go
> +		return c.JSON(500, pkg.NewError(err))
pkgがスコープが大きいので、エラーなら、エラー、ロギングならロギング用のパッケージで分けましょう。

2023-08-27 01:30 UTC, TakumaKurosawa commented on interfaces/controller/user/user.go
> +	err := uc.uu.DeleteById(user)
`ByXXX` のような関数でモデルを受け取る実装はあまり見ないですね。
今回の場合だと、 `ById` なので、 `DeleteById(uint(id))` としてあげた方が良さそう。

2023-08-27 01:30 UTC, TakumaKurosawa commented on usecase/reservation/reservation.go
> +func (ru *ReservationUsecase) Add(r model.Reservation) (*model.Reservation, error) {
大体、関数の引数と返り値に指定するStructの型はポインタであることが多いです。

```suggestion
func (ru *ReservationUsecase) Add(r *model.Reservation) (*model.Reservation, error) {
```

2023-08-27 01:30 UTC, TakumaKurosawa commented on usecase/reservation/reservation.go
> +func (ru *ReservationUsecase) Add(r model.Reservation) (*model.Reservation, error) {
今の実装だと、Controller層がDomain層を参照できてしまっているので、UseCaseにI/Oを作ってあげた方が良さそう。

```suggestion
func (ru *ReservationUsecase) Add(input *AddInput) (*AddOutput, error) {
```

2023-08-27 01:30 UTC, TakumaKurosawa commented on usecase/user/user.go
> +	tokenString, err := token.SignedString([]byte(os.Getenv("SECRET")))
`os.Getenv()` を一度だけ実行したら値が引き回せるようにするには？

2023-08-28 10:40 UTC, TakumaKurosawa commented on infrastructure/mysql.go
> +/*
こちらで修正しました！
https://github.com/temmie524/room-management-app-backend/pull/25/commits/415373ab0d8c27bae9db15e749d571dfbd54fd14

2023-08-28 15:13 UTC, temmie524 commented on interfaces/controller/reservation/reservation.go
>  	id, _ := strconv.Atoi(c.Param("id"))
https://github.com/temmie524/room-management-app-backend/pull/25/commits/d9b0d29e13e72c97d944ea5e2be2dba6d17d6b51
修正しました

2023-08-29 02:36 UTC, temmie524 commented on usecase/user/user.go
> +	tokenString, err := token.SignedString([]byte(os.Getenv("SECRET")))
[de55ba8](https://github.com/temmie524/room-management-app-backend/pull/25/commits/de55ba85739defb61fad61261d1627354f7ba234)

ConfigのStruct作ってコンストラクタに埋め込みました。
ちょっと自信ないです。

2023-08-29 06:22 UTC, temmie524 commented on usecase/reservation/reservation.go
> +func (ru *ReservationUsecase) Add(r model.Reservation) (*model.Reservation, error) {
https://github.com/temmie524/room-management-app-backend/pull/25/commits/3f49e4e3fe38b4b5a8b20366bbe20769320b06a1
こちらもひとまずUserのUpdateのみ実装しました。動作確認もできています。

2023-08-29 10:42 UTC, TakumaKurosawa commented on config/config.go
> +	FE_URL     string
Goの慣習的に、CamelCaseで書くことが多い。

```go
SecretKey string
```

2023-08-30 08:36 UTC, temmie524 commented on usecase/reservation/reservation.go
> +func (ru *ReservationUsecase) Add(r model.Reservation) (*model.Reservation, error) {
- UserI/O続き。他の関数にも実装。
[cda2139](https://github.com/temmie524/room-management-app-backend/pull/25/commits/cda21396b9a75d81e566d170dff4f5f6d68dc386)
- RoomI/O
 [3571867](https://github.com/temmie524/room-management-app-backend/pull/25/commits/3571867cbebb3161f9ff2fb52a44469550e6ada2)

- ReservationI/O (commitメッセージがRoomになっていますが、正しくはReservationのI/O実装です)
[8f5419f](https://github.com/temmie524/room-management-app-backend/pull/25/commits/8f5419f40925c70aa80b360080c06d774c45ca78)

2023-08-30 08:47 UTC, temmie524 commented on config/config.go
> +	FE_URL     string
修正
[20d7796](https://github.com/temmie524/room-management-app-backend/pull/25/commits/20d7796ed7b7af11ae9ca9e7d98642c8ad7d0734)

2023-08-30 09:10 UTC, temmie524 commented on infrastructure/router.go
> +	"room_app_back/config"
レポジトリを一つにするということで、package name をbackendに修正しました。
[2485f93](https://github.com/temmie524/room-management-app-backend/pull/25/commits/2485f93291cf8e8ab9a2022bae6173e356c283ee)

2023-08-31 10:37 UTC, TakumaKurosawa approved these changes
LGTM

2023-09-01 13:05 UTC, merged